Classes metiers
Xzeno15150/heroes-of-transnya-quarkus pull request #2
Opened 2023-05-26 09:47 UTC by erpoint

J'ai fait les classes métier \(0^u^0)/

2023-05-26 09:54 UTC, Neitah commented on src/main/java/fr/multiplatform/hot/entities/character/Character.java
> +    private List<ItemPartial> items;
Déplacer ça avec les autres attributs

2023-05-27 06:30 UTC, erpoint commented on src/main/java/fr/multiplatform/hot/entities/character/Character.java
> +    private List<ItemPartial> items;
:+1:

2023-05-27 06:55 UTC, Xzeno15150 requested changes
Quelques chnngement mineurs

2023-05-27 06:55 UTC, Xzeno15150 commented on src/main/java/fr/multiplatform/hot/entities/HealthPoint.java
> +    public HealthPoint(int max) {
il manque le constructeur vide

2023-05-27 06:55 UTC, Xzeno15150 commented on src/main/java/fr/multiplatform/hot/entities/HealthPoint.java
> +    public void setMax(int max) {
setter fluent ?

2023-05-27 06:55 UTC, Xzeno15150 commented on src/main/java/fr/multiplatform/hot/entities/character/Character.java
> +    public Character() {
la il y est je suis joie

2023-05-27 06:55 UTC, Xzeno15150 commented on src/main/java/fr/multiplatform/hot/entities/character/Character.java
> +    private HealthPoint healthPoints;
pourquoi healthPoint au pluriel ?

2023-05-27 06:55 UTC, Xzeno15150 commented on src/main/java/fr/multiplatform/hot/entities/Statistic.java
> +    public Statistic(int strength, int intelligence) {
il manque le constructeur vide

2023-05-27 06:55 UTC, Xzeno15150 commented on src/main/java/fr/multiplatform/hot/entities/character/CharacterPartial.java
> +    public CharacterPartial(String id, String name, String element, UserPartial user) {
il manque le constructeur vide

2023-05-27 06:55 UTC, Xzeno15150 commented on src/main/java/fr/multiplatform/hot/entities/skill/Skill.java
> +    public Skill(String name, String description, String imagePath) {
il manque le constructeur vide

2023-05-27 06:55 UTC, Xzeno15150 commented on src/main/java/fr/multiplatform/hot/entities/skill/SkillPartial.java
> +    public SkillPartial(String id, String name) {
il manque le constructeur vide

2023-05-27 07:17 UTC, erpoint commented on src/main/java/fr/multiplatform/hot/entities/character/Character.java
> +    public Character() {
:smile:

2023-05-27 07:19 UTC, erpoint commented on src/main/java/fr/multiplatform/hot/entities/character/Character.java
> +    private HealthPoint healthPoints;
parce que y a plusieurs points mais oui y a qu'un obj c'est pas une liste.
A voir si ca a du sens ce que je dit

2023-05-27 07:20 UTC, erpoint commented on src/main/java/fr/multiplatform/hot/entities/character/Character.java
> +    private HealthPoint healthPoints;
réponse orale

2023-05-27 11:19 UTC, Xzeno15150 approved these changes

2023-05-27 16:54 UTC, merged